
/* Converted by LeonarDucky v1.0 */

#include <Keyboard.h>
void setup() {
Keyboard.begin();
delay(3000);
// Lock Me 0.3 - Script opens Notepad and types a message concerning locking the computer - by SurfKahuna (RJC)
delay(200);
Keyboard.press(KEY_LEFT_GUI);
Keyboard.press('r');
Keyboard.releaseAll();
delay(200);
Keyboard.print("notepad.exe");
delay(200);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
delay(300);
Keyboard.print(", ,\\ ,'\\,'\\ ,'\\ ,\\ ,");
delay(10);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print(",  ,\\/ \\' `'     `   '  /|");
delay(10);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print("|\\/                      |");
delay(10);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print(":                        |");
delay(10);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print(":                        |");
delay(10);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print("|                       |");
delay(10);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print("|                       |");
delay(10);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print(":               -.     _|");
delay(10);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print(":                \\     `.");
delay(10);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print("|         ________:______\\");
delay(10);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print(":       ,'o       / o    ,");
delay(10);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print(":       \\       ,'-----./");
delay(10);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print("\\_      `--.--'        )");
delay(10);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print(",` `.              ,---'|");
delay(10);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print(": `                     |");
delay(10);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print("`,-'                   |");
delay(10);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print("/      ,---.          ,'");
delay(10);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print(",-'            `-,------'");
delay(10);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print("`.        ,--'");
delay(10);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print("`-.____/");
delay(10);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print("\\");
delay(200);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
delay(200);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print("I will learn to lock my computer.");
delay(200);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print("I will learn to lock my computer.");
delay(200);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print("I will learn to lock my computer.");
delay(200);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print("I will learn to lock my computer.");
delay(200);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print("I will learn to lock my computer.");
delay(200);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print("I will learn to lock my computer.");
delay(200);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print("I will learn to lock my computer.");
delay(200);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print("I will learn to lock my computer.");
delay(200);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print("I will learn to lock my computer.");
delay(200);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print("I will learn to lock my computer.");
delay(200);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
delay(200);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print("There, just like Bart Simpson.");
delay(200);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
delay(200);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print("Please remember to lock your computer when you step away from your desk.");
delay(200);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
delay(200);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
Keyboard.print("Thank you.");
delay(200);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
delay(100);
delay(200);
Keyboard.press(KEY_LEFT_ALT);
Keyboard.press(32);
Keyboard.releaseAll();
Keyboard.print("x");
}
void loop() {}